name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Verify GITHUB_TOKEN Permissions
      - name: Verify GITHUB_TOKEN Permissions
        run: |
          echo "Token permissions:"
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ github.repository }}/actions/permissions

      # Step 2: Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v2

      # Step 3: Set up JDK for Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      # Step 4: Cache Gradle files to speed up builds
      - name: Cache Gradle files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Step 5: Grant execution permissions for gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Step 6: Build the project in debug mode
      - name: Build with Gradle (debug)
        run: ./gradlew assembleDebug

      # Step 7: Create a GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.0
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Upload APK to GitHub Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive
