name: Android CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v2

      # Step 2: Set up JDK for Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      # Step 3: Cache Gradle files to speed up builds
      - name: Cache Gradle files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Step 4: Grant execution permissions for gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Step 5: Build the project in debug mode
      - name: Build with Gradle (debug)
        run: ./gradlew assembleDebug  # This will create the debug APK

      # Step 6: Upload the generated debug APK as an artifact
      - name: Upload APK
        if: always()  # Always upload the artifact, even if the build fails
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk  # Name for the uploaded artifact
          path: app/build/outputs/apk/debug/app-debug.apk  # Path to the debug APK
